### ISSUE TITLE
Ikea Tradfri Wireless Dimmer

### ISSUE THREAD

**Issue by smulle48** [Jeedom-Zigate/jeedom-plugin-zigate#144]
Version plugin 1.2.2
Version lib 0.28.1 / 0.28
Version firmware 3.0f

After upgrading the lib, the IKEA wireless dimmer does not work. When added is shows up as an generic device with only refresh. If I downgrade to 0.27.9 it works, and the dimmer is added correctly with all values and commands
![skaermbillede 2019-02-22 kl 15 24 16](https://user-images.githubusercontent.com/24297824/53248428-00fc6700-36b6-11e9-9fa9-416e1dcc0213.png)

**Comment by doudz** [comment]
will be fixed on lib 0.28.2

**Comment by smulle48** [comment]
sounds great :-)

**Comment by smulle48** [comment]
Hi again

Something is completely wrong with the IKEA support.

Tried to update to 0.28.2 and the dimmer is recognized as an IKEA dimmer, but the link quality is 0. I tried to refresh the dimmer and the "Commandes" page is filled with "weird" information :-)

I then tried to downgrade to 0.27.9 and the link quality is shown correctly.

One problem with all versions of the lib, is that I can't connect the dimmer to any bulb.

For testing purpose, I tried to install Abielle and everything work as it should. I can add the dimmer to the ZigBee network, connect the bulb to the dimmer, and control everything from Jeedom.

Is it correct that I can't see the dimmer state in Jeedom when using this plugin?? (eg. 10%) In Abielle I can see the dimmer state and the bulb state.
![skaermbillede 2019-02-25 kl 19 56 48](https://user-images.githubusercontent.com/24297824/53361173-978b8b00-3937-11e9-86c2-55fb04b2718b.png)
![skaermbillede 2019-02-25 kl 19 57 00](https://user-images.githubusercontent.com/24297824/53361200-99ede500-3937-11e9-9406-5b8ca12deb3f.png)
![skaermbillede 2019-02-25 kl 19 57 11](https://user-images.githubusercontent.com/24297824/53361215-9bb7a880-3937-11e9-9a39-54296939024a.png)
![skaermbillede 2019-02-25 kl 19 57 18](https://user-images.githubusercontent.com/24297824/53361249-9fe3c600-3937-11e9-8328-13fb7f432dc6.png)

**Comment by doudz** [comment]
The remote_level_button is not getting change using the remote ?

**Comment by smulle48** [comment]
No. Not at all.

This is how it looks on the dashboard
![skaermbillede 2019-02-26 kl 06 32 08](https://user-images.githubusercontent.com/24297824/53389666-76a35400-3990-11e9-93e3-8c504ef5a3f1.png)

**Comment by doudz** [comment]
Looks like the device "type" is missing, maybe discovery hasn't work.
Could you try to call "Découverte" on that device ? Remember to awake the remote to get change.

**Comment by doudz** [comment]
About the Link Quality, it should works, if not maybe the device is not paired ?
When you said you can't connect the bulb and the dimmer, what are you doing with abeille ? and with zigate ?

**Comment by doudz** [comment]
I ordered a bulb and a dimmer, it will be more easy to test

**Comment by smulle48** [comment]
I have tried to include/exclude it multiple times but nothing changed. I even tried to PDM reset. It’s like something is blocking the dimmer when included so I can’t connect the dimmer with the bulb. I tried “Découverte” and it was after that, that all the entireties when number showed up on the commandes page.

In Abeille I can connect the dimmer to ZiGate and it shows on the dashboard as a dimmer correctly. I can then afterwards connect the dimmer to the bulb as original with the Ikea Tradfri. It then afterwards shows up on the dashboard correctly as a bulb, so both a bulb and a dimmer is on the dashboard

**Comment by doudz** [comment]
ok I understand, there's some things that need to be clarified :
- The dimmer can be paired to zigate : before 3.0f, zigate can only get some info like battery, with 3.0f zigate can catch more events, like on,off or level change. To do that both dimmer and zigate need to be in the same zigbee group (and in the future I'll try to do it automagically)

- The bulb can be paired to zigate and can be control by zigate

- When you pair the dimmer to the bulb using Ikea style, technically the dimmer create a zigbee group and put the bulb into the same group in order to control it because the dimmer send commands (on/off/level) to a zigbee group not to a device.
So if you put the zigate in the same group, you'll be able to catch events from dimmer. (group list can be retrieve using zigate command 0x0062)

Beside that, as convenient functions, for the dimmer Abeille add commands on the jeedom object to send on / off and level to the zigbee **group** but really it as nothing to do with the dimmer
Any time we could create a button and send a ON command to a group and if there's some bulbs in that group they will be turn on.

**Comment by doudz** [comment]
You can't control the dimmer using zigate, Abeille just mimic the dimmer.
If this is what you want, maybe we can add it in a next release

**Comment by smulle48** [comment]
As long as I can see battery status, link quality and be able to add bulbs directly with the dimmer, I’m happy :-)

One thing though that could be nice, was to be able to see which devices in groups just like the ikea app, and to be able to move a device from group to group.

**Comment by doudz** [comment]
This will be added soon ;)

**Comment by doudz** [comment]
I planned to :
- Automatically add zigate to group 0000 (to be able to catch event)
- Automatically add ikea remote to group 0000 (to catch event)
- Add UI to manage groups per device

**Comment by smulle48** [comment]
You are a champ :-)

I really appreciate the great work you are doing.

Btw. Is the plugin working better in HA? Maybe I should try it again. Been over 6 months since I’ve tried it last time:-)

**Comment by doudz** [comment]
IMHO HA is better :smile:

**Comment by smulle48** [comment]
Is the zigbee plugin for HA just as good as yours for Jeedom?

**Comment by doudz** [comment]
Since you seems interested by battery informations you have to know that there's no battery panel in HA (not natively) but you can still check battery level per device
some screen of my HA
![image](https://user-images.githubusercontent.com/1262548/53474283-f4d52880-3a6c-11e9-8e05-07dab182d99a.png)
![image](https://user-images.githubusercontent.com/1262548/53474288-fb63a000-3a6c-11e9-9948-2de4daceb77a.png)
![image](https://user-images.githubusercontent.com/1262548/53474315-09192580-3a6d-11e9-97ed-5e6f81ac61f1.png)
![image](https://user-images.githubusercontent.com/1262548/53474346-1e8e4f80-3a6d-11e9-95b8-0ac39f020738.png)
![image](https://user-images.githubusercontent.com/1262548/53474384-3534a680-3a6d-11e9-8e1f-ae90774829f5.png)
![image](https://user-images.githubusercontent.com/1262548/53474395-3f56a500-3a6d-11e9-81e5-1b02d220e0fc.png)
![image](https://user-images.githubusercontent.com/1262548/53474407-4aa9d080-3a6d-11e9-8cbe-3a967959fed6.png)

**Comment by doudz** [comment]
https://github.com/doudz/homeassistant-zigate

**Comment by smulle48** [comment]
That’s really nice:-)

Think I’ll take it for a spin later today:-)

**Comment by smulle48** [comment]
is it only the ZiGate folder I have to clone into custom_components ?

What about the panels folder?

**Comment by doudz** [comment]
The zigate folder should be in custom_components and the panels folder at the same level of custom_components

**Comment by doudz** [comment]
And you can copy your zigate.jso n file from Jeedom to your ha config folder to keep your config

**Comment by smulle48** [comment]
can I expose it to HomeKit? :-)

**Comment by doudz** [comment]
Yes https://www.home-assistant.io/components/homekit_controller/

**Comment by smulle48** [comment]
Which one will you recommend. Hass.io or Hassbian? :-D

**Comment by doudz** [comment]
No Idea, I use a custom install.
https://community.home-assistant.io/t/what-is-the-difference-between-hassbian-and-hass-io/35108

**Comment by doudz** [comment]
Closing, since I made a test and it's working

**Comment by smulle48** [comment]
@doudz 

Maybe I'm just a complete fool, but now the Link Quality is not shown in Jeedom. I can see the LQI values in the json file though.

And now my Aqara wireless switch gets disabled after a day or so :-(

![skaermbillede 2019-03-04 kl 15 57 46](https://user-images.githubusercontent.com/24297824/53741257-467b1a00-3e96-11e9-9bd2-121c0f241dee.png)
![skaermbillede 2019-03-04 kl 15 58 10](https://user-images.githubusercontent.com/24297824/53741287-54c93600-3e96-11e9-9804-952d0bba56fd.png)
![skaermbillede 2019-03-04 kl 16 00 43](https://user-images.githubusercontent.com/24297824/53741439-af629200-3e96-11e9-819c-dee04dc79212.png)

**Comment by doudz** [comment]
If you click on "Synchroniser" the LQI should appear.
You could also try to open "informations" of the jeedom object to see differents values like lqi or lastCommunication

**Comment by smulle48** [comment]
It did not work, Now I'm installing on a fresh Jeedom to see if it helps.

Looks like Xiaomi problems are known, sadly :-( Hope it will be fixed soon. I'm planning to use the switch as a door bell, but that's not an option atm, when Xiaomi devices are so unstable

**Comment by doudz** [comment]
I'm not sure you use the last release of the plugin, on the "Santé" page  I see "Rssi" but it has been renamed LQI

**Comment by smulle48** [comment]
> I'm not sure you use the last release of the plugin, on the "Santé" page I see "Rssi" but it has been renamed LQI

I'm on the latest release, and it still says Rssi. Maybe it's changed in the pre-release?

**Comment by smulle48** [comment]
Do you know how long it will take before the update is pushed to the Jeedom market? :-)

**Comment by doudz** [comment]
Jeedom Market is updated every night

**Comment by smulle48** [comment]
Okay. Then I have to wait until tomorrow to test it, unless there’s a way to update it manually

**Comment by smulle48** [comment]
working now :-)
